os:
  - osx
  - windows

language: node_js

node_js:
  - node

cache:
  - yarn
  - cargo

before_install:
  # Install Rust and Cargo
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      choco install windows-sdk-10.0
      choco install rust
    else
      curl https://sh.rustup.rs -sSf > /tmp/rustup.sh && /
      sh /tmp/rustup.sh -y && /
      export PATH="$HOME/.cargo/bin:$PATH" && /
      source "$HOME/.cargo/env"
    fi

  - node -v
  - npm -v
  - yarn global add yarn@latest
  - yarn

script:
  - yarn upload-binary || exit 0;
